#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

packages=()

for line in `git diff --name-only --cached`
do
  if [[ $line == *"packages/"* ]]
  then
    packagePath=$( echo $line | cut -d'/' -f-2 )

    if [[ ! " ${packages[*]} " =~ " ${packagePath} " ]]; then
      packages+=($packagePath)
    fi
  fi
done

rootDir=$PWD

for package in "${packages[@]}"
do
  packageAbsolutePath=$rootDir'/'$package
	cd $packageAbsolutePath
  echo '----- '$package' -----> lint checking...'
  yarn lint
  echo '----- '$package' -----> building...'
  yarn build
done

cd $rootDir
git add .
